import 'package:flutter/material.dart';
import '../../core/network/api_client.dart';
import '../../core/storage/secure_storage_service.dart';
import '../../core/theme/app_colors.dart';
import '../../models/catalog_models.dart';
import '../../models/youth_model.dart';

class YouthFormScreen extends StatefulWidget { const YouthFormScreen({super.key,this.youth}); final YouthModel? youth; @override State<YouthFormScreen> createState()=>_YouthFormScreenState(); }
class _YouthFormScreenState extends State<YouthFormScreen>{
 final _api=ApiClient(SecureStorageService()); final _name=TextEditingController(); final _phone=TextEditingController(); List<TribeModel> _tribes=[]; List<ProjectModel> _projects=[]; String? _tribe; String? _project; bool _loading=true; bool _saving=false;
 @override void initState(){super.initState(); _name.text=widget.youth?.fullName??'';_phone.text=widget.youth?.phone??'';_tribe=widget.youth?.tribeId;_project=widget.youth?.projectId;_load();}
 Future<void> _load()async{final r=await Future.wait([_api.dio.get('/api/tribes'),_api.dio.get('/api/projects')]);_tribes=(r[0].data as List).map((e)=>TribeModel.fromJson(Map<String,dynamic>.from(e))).toList();_projects=(r[1].data as List).map((e)=>ProjectModel.fromJson(Map<String,dynamic>.from(e))).toList();if(mounted)setState(()=>_loading=false);}
 Future<void> _save()async{if(_name.text.trim().length<2||_phone.text.trim().length<5||_tribe==null){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Completa nombres, celular y tribu.')));return;}setState(()=>_saving=true);final data={'full_name':_name.text.trim(),'phone':_phone.text.trim(),'tribe_id':_tribe,'project_id':_project};if(widget.youth==null){await _api.dio.post('/api/youth',data:data);}else{await _api.dio.put('/api/youth/${widget.youth!.id}',data:data);}if(mounted)Navigator.pop(context,true);}
 @override Widget build(BuildContext context){final projects=_projects.where((p)=>p.tribeId==null||p.tribeId==_tribe).toList();return Scaffold(appBar:AppBar(title:Text(widget.youth==null?'Nuevo joven':'Editar joven')),body:_loading?const Center(child:CircularProgressIndicator()):ListView(padding:const EdgeInsets.all(18),children:[const CircleAvatar(radius:42,child:Icon(Icons.person_rounded,size:44)),const SizedBox(height:22),TextField(controller:_name,decoration:const InputDecoration(labelText:'Nombres *',hintText:'Ej. Ana Valentina')),const SizedBox(height:12),TextField(controller:_phone,keyboardType:TextInputType.phone,decoration:const InputDecoration(labelText:'Celular *',hintText:'Ej. 099 123 4567')),const SizedBox(height:12),DropdownButtonFormField<String>(value:_tribe,decoration:const InputDecoration(labelText:'Tribu *'),items:_tribes.map((t)=>DropdownMenuItem(value:t.id,child:Text(t.name))).toList(),onChanged:(v)=>setState((){_tribe=v;if(_project!=null&&!projects.any((p)=>p.id==_project))_project=null;})),const SizedBox(height:12),DropdownButtonFormField<String?>(value:_project,decoration:const InputDecoration(labelText:'Proyecto (opcional)'),items:[const DropdownMenuItem(value:null,child:Text('Sin proyecto')),...projects.map((p)=>DropdownMenuItem(value:p.id,child:Text(p.name)))],onChanged:(v)=>setState(()=>_project=v)),const SizedBox(height:24),SizedBox(height:52,child:FilledButton.icon(style:FilledButton.styleFrom(backgroundColor:AppColors.red,foregroundColor:Colors.white),onPressed:_saving?null:_save,icon:const Icon(Icons.save_rounded),label:Text(_saving?'Guardando...':'Guardar')))]));}
}
