import 'package:flutter/material.dart';
import 'package:qr_flutter/qr_flutter.dart';
import '../../core/network/api_client.dart';
import '../../core/storage/secure_storage_service.dart';
import '../../core/theme/app_colors.dart';
import '../../models/youth_model.dart';
import 'youth_form_screen.dart';

class YouthProfileScreen extends StatefulWidget { const YouthProfileScreen({super.key,required this.youth}); final YouthModel youth; @override State<YouthProfileScreen> createState()=>_YouthProfileScreenState(); }
class _YouthProfileScreenState extends State<YouthProfileScreen>{late YouthModel _youth=widget.youth;final _api=ApiClient(SecureStorageService());Future<void>_regenerate()async{final r=await _api.dio.post('/api/youth/${_youth.id}/regenerate-qr');setState(()=>_youth=YouthModel.fromJson(Map<String,dynamic>.from(r.data)));}
 @override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Perfil del joven'),actions:[PopupMenuButton<String>(onSelected:(v)async{if(v=='edit'){final changed=await Navigator.push<bool>(context,MaterialPageRoute(builder:(_)=>YouthFormScreen(youth:_youth)));if(changed==true&&mounted)Navigator.pop(context);}if(v=='qr')_regenerate();},itemBuilder:(_)=>const[PopupMenuItem(value:'edit',child:Text('Editar información')),PopupMenuItem(value:'qr',child:Text('Generar nuevo QR'))])]),body:ListView(padding:const EdgeInsets.all(20),children:[CircleAvatar(radius:42,backgroundColor:AppColors.navy,foregroundColor:Colors.white,child:Text(_youth.fullName.split(' ').take(2).map((x)=>x[0]).join(),style:const TextStyle(fontSize:26,fontWeight:FontWeight.bold))),const SizedBox(height:14),Text(_youth.fullName,textAlign:TextAlign.center,style:Theme.of(context).textTheme.headlineSmall?.copyWith(fontWeight:FontWeight.w800)),const SizedBox(height:22),Card(child:Padding(padding:const EdgeInsets.all(20),child:Column(children:[QrImageView(data:_youth.qrToken,size:220,backgroundColor:Colors.white),const SizedBox(height:8),Text('Código personal',style:Theme.of(context).textTheme.titleMedium?.copyWith(fontWeight:FontWeight.w700)),const Text('Este QR no contiene nombres ni celular.',textAlign:TextAlign.center)]))),const SizedBox(height:14),Card(child:ListTile(leading:const Icon(Icons.phone_rounded,color:AppColors.navy),title:const Text('Celular'),subtitle:Text(_youth.phone))),const SizedBox(height:8),const Text('Guarda o imprime este QR para que el joven pueda registrar su asistencia desde la pantalla pública.',textAlign:TextAlign.center)]));}
