import 'package:flutter/material.dart';
import '../../core/network/api_client.dart';
import '../../core/storage/secure_storage_service.dart';
import '../../core/theme/app_colors.dart';
import '../../models/catalog_models.dart';

class ProjectsScreen extends StatefulWidget{const ProjectsScreen({super.key});@override State<ProjectsScreen>createState()=>_ProjectsScreenState();}
class _ProjectsScreenState extends State<ProjectsScreen>{final _api=ApiClient(SecureStorageService());List<ProjectModel>_items=[];List<TribeModel>_tribes=[];bool _loading=true;@override void initState(){super.initState();_load();}Future<void>_load()async{final r=await Future.wait([_api.dio.get('/api/projects'),_api.dio.get('/api/tribes')]);_items=(r[0].data as List).map((e)=>ProjectModel.fromJson(Map<String,dynamic>.from(e))).toList();_tribes=(r[1].data as List).map((e)=>TribeModel.fromJson(Map<String,dynamic>.from(e))).toList();if(mounted)setState(()=>_loading=false);}String _tribeName(String? id)=>_tribes.where((t)=>t.id==id).map((t)=>t.name).firstOrNull??'Todas / General';Future<void>_edit([ProjectModel? item])async{final c=TextEditingController(text:item?.name??'');String? tribe=item?.tribeId;final ok=await showDialog<bool>(context:context,builder:(ctx)=>StatefulBuilder(builder:(ctx,setLocal)=>AlertDialog(title:Text(item==null?'Nuevo proyecto':'Editar proyecto'),content:Column(mainAxisSize:MainAxisSize.min,children:[TextField(controller:c,decoration:const InputDecoration(labelText:'Nombre')),const SizedBox(height:10),DropdownButtonFormField<String?>(value:tribe,decoration:const InputDecoration(labelText:'Tribu'),items:[const DropdownMenuItem(value:null,child:Text('General')),..._tribes.map((t)=>DropdownMenuItem(value:t.id,child:Text(t.name)))],onChanged:(v)=>setLocal(()=>tribe=v))]),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(ctx,true),child:const Text('Guardar'))])));if(ok==true&&c.text.trim().isNotEmpty){final data={'name':c.text.trim(),'tribe_id':tribe};if(item==null){await _api.dio.post('/api/projects',data:data);}else{await _api.dio.put('/api/projects/${item.id}',data:data);}await _load();}}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Proyectos')),floatingActionButton:FloatingActionButton.extended(backgroundColor:AppColors.red,foregroundColor:Colors.white,onPressed:()=>_edit(),icon:const Icon(Icons.add),label:const Text('Nuevo proyecto')),body:_loading?const Center(child:CircularProgressIndicator()):ListView.separated(padding:const EdgeInsets.all(16),itemCount:_items.length,separatorBuilder:(_,__)=>const SizedBox(height:8),itemBuilder:(_,i){final p=_items[i];return Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.sports_soccer_rounded)),title:Text(p.name,style:const TextStyle(fontWeight:FontWeight.w800)),subtitle:Text(_tribeName(p.tribeId)),trailing:IconButton(onPressed:()=>_edit(p),icon:const Icon(Icons.edit_outlined))));}));}

extension _FirstOrNull<T> on Iterable<T>{T? get firstOrNull=>isEmpty?null:first;}
