import 'package:flutter/material.dart';
import '../../core/network/api_client.dart';
import '../../core/storage/secure_storage_service.dart';
import '../../core/theme/app_colors.dart';
import '../../models/catalog_models.dart';

class TribesScreen extends StatefulWidget{const TribesScreen({super.key});@override State<TribesScreen>createState()=>_TribesScreenState();}
class _TribesScreenState extends State<TribesScreen>{final _api=ApiClient(SecureStorageService());List<TribeModel>_items=[];bool _loading=true;@override void initState(){super.initState();_load();}Future<void>_load()async{final r=await _api.dio.get('/api/tribes');_items=(r.data as List).map((e)=>TribeModel.fromJson(Map<String,dynamic>.from(e))).toList();if(mounted)setState(()=>_loading=false);}Future<void>_edit([TribeModel? item])async{final c=TextEditingController(text:item?.name??'');final ok=await showDialog<bool>(context:context,builder:(ctx)=>AlertDialog(title:Text(item==null?'Nueva tribu':'Editar tribu'),content:TextField(controller:c,decoration:const InputDecoration(labelText:'Nombre')),actions:[TextButton(onPressed:()=>Navigator.pop(ctx,false),child:const Text('Cancelar')),FilledButton(onPressed:()=>Navigator.pop(ctx,true),child:const Text('Guardar'))]));if(ok==true&&c.text.trim().isNotEmpty){if(item==null){await _api.dio.post('/api/tribes',data:{'name':c.text.trim()});}else{await _api.dio.put('/api/tribes/${item.id}',data:{'name':c.text.trim()});}await _load();}}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Tribus')),floatingActionButton:FloatingActionButton.extended(backgroundColor:AppColors.red,foregroundColor:Colors.white,onPressed:()=>_edit(),icon:const Icon(Icons.add),label:const Text('Nueva tribu')),body:_loading?const Center(child:CircularProgressIndicator()):ListView.separated(padding:const EdgeInsets.all(16),itemCount:_items.length,separatorBuilder:(_,__)=>const SizedBox(height:8),itemBuilder:(_,i){final t=_items[i];return Card(child:ListTile(leading:const CircleAvatar(child:Icon(Icons.diversity_3_rounded)),title:Text(t.name,style:const TextStyle(fontWeight:FontWeight.w800)),trailing:IconButton(onPressed:()=>_edit(t),icon:const Icon(Icons.edit_outlined))));}));}
