import 'package:flutter/material.dart';
import '../../core/network/api_client.dart';
import '../../core/storage/secure_storage_service.dart';
import '../../core/theme/app_colors.dart';
import '../../models/user_model.dart';

class UserPermissionsScreen extends StatefulWidget{const UserPermissionsScreen({super.key,required this.user});final UserModel user;@override State<UserPermissionsScreen>createState()=>_UserPermissionsScreenState();}
class _UserPermissionsScreenState extends State<UserPermissionsScreen>{final _api=ApiClient(SecureStorageService());List<Map<String,dynamic>>_items=[];bool _loading=true;@override void initState(){super.initState();_load();}Future<void>_load()async{final r=await _api.dio.get('/api/users/${widget.user.id}/permissions');_items=(r.data as List).map((e)=>Map<String,dynamic>.from(e)).toList();if(mounted)setState(()=>_loading=false);}Future<void>_save()async{final keys=_items.where((e)=>e['enabled']==true).map((e)=>e['key']).toList();await _api.dio.put('/api/users/${widget.user.id}/permissions',data:{'menu_keys':keys});if(mounted){ScaffoldMessenger.of(context).showSnackBar(const SnackBar(content:Text('Menús actualizados. Se aplicarán en el próximo inicio de sesión.')));Navigator.pop(context);}}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:const Text('Asignar menús')),body:_loading?const Center(child:CircularProgressIndicator()):Column(children:[Padding(padding:const EdgeInsets.all(16),child:Text('Selecciona qué módulos podrá ver ${widget.user.fullName}.',style:const TextStyle(fontWeight:FontWeight.w600))),Expanded(child:ListView(children:_items.map((e)=>SwitchListTile(activeColor:AppColors.red,title:Text(e['label']?.toString()??''),subtitle:Text(e['description']?.toString()??''),value:e['enabled']==true,onChanged:(v)=>setState(()=>e['enabled']=v))).toList())),SafeArea(top:false,child:Padding(padding:const EdgeInsets.all(16),child:SizedBox(width:double.infinity,height:52,child:FilledButton.icon(style:FilledButton.styleFrom(backgroundColor:AppColors.red,foregroundColor:Colors.white),onPressed:_save,icon:const Icon(Icons.save),label:const Text('Guardar permisos'))))) ]));}
