import 'package:flutter/material.dart';
import '../../core/network/api_client.dart';
import '../../core/storage/secure_storage_service.dart';
import '../../core/theme/app_colors.dart';
import '../../models/user_model.dart';

class UserFormScreen extends StatefulWidget{const UserFormScreen({super.key,this.user});final UserModel?user;@override State<UserFormScreen>createState()=>_UserFormScreenState();}
class _UserFormScreenState extends State<UserFormScreen>{final _api=ApiClient(SecureStorageService());final _name=TextEditingController();final _username=TextEditingController();final _password=TextEditingController();String _role='COORDINATOR';@override void initState(){super.initState();_name.text=widget.user?.fullName??'';_username.text=widget.user?.username??'';_role=widget.user?.isSuperAdmin==true?'SUPER_ADMIN':'COORDINATOR';}Future<void>_save()async{if(widget.user==null){await _api.dio.post('/api/users',data:{'full_name':_name.text.trim(),'username':_username.text.trim(),'password':_password.text,'role':_role});}else{await _api.dio.put('/api/users/${widget.user!.id}',data:{'full_name':_name.text.trim(),'role':_role});}if(mounted)Navigator.pop(context,true);}
@override Widget build(BuildContext context)=>Scaffold(appBar:AppBar(title:Text(widget.user==null?'Nuevo usuario':'Editar usuario')),body:ListView(padding:const EdgeInsets.all(18),children:[TextField(controller:_name,decoration:const InputDecoration(labelText:'Nombre completo')),const SizedBox(height:12),TextField(controller:_username,enabled:widget.user==null,decoration:const InputDecoration(labelText:'Usuario')),if(widget.user==null)...[const SizedBox(height:12),TextField(controller:_password,obscureText:true,decoration:const InputDecoration(labelText:'Contraseña temporal'))],const SizedBox(height:12),DropdownButtonFormField<String>(value:_role,decoration:const InputDecoration(labelText:'Rol'),items:const[DropdownMenuItem(value:'SUPER_ADMIN',child:Text('Super administrador')),DropdownMenuItem(value:'COORDINATOR',child:Text('Coordinador'))],onChanged:(v)=>setState(()=>_role=v!)),const SizedBox(height:22),SizedBox(height:52,child:FilledButton.icon(style:FilledButton.styleFrom(backgroundColor:AppColors.red,foregroundColor:Colors.white),onPressed:_save,icon:const Icon(Icons.save),label:const Text('Guardar')))]));}
